<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<meta name="description" content="">';
echo '<meta name="author" content="">';
echo '<link rel="shortcut icon" href="assets/ico/favicon.ico">';
echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>';
echo '<link rel="stylesheet" href="form.css" >';
echo '<script src="form.js"></script>';
echo '';
echo '<title>Myles Dawborn Portfolio</title>';
echo '';
echo '<!-- Bootstrap core CSS -->';
echo '<link href="assets/css/bootstrap.css" rel="stylesheet">';
echo '';
echo '<!-- Custom styles for this template -->';
echo '<link href="assets/css/style.css" rel="stylesheet">';
echo '<link href="assets/css/font-awesome.min.css" rel="stylesheet">';
echo '';
echo '<!-- Just for debugging purposes. Dont actually copy this line! -->';
echo '<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->';
echo '';
echo '<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->';
echo '<!--[if lt IE 9]>';
echo '<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>';
echo '<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>';
echo '<![endif]-->';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<!-- Static navbar -->';
echo '<div class="navbar navbar-default navbar-fixed-top" role="navigation">';
echo '<div class="container">';
echo '<div class="navbar-header">';
echo '<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">';
echo '<span class="sr-only">Toggle navigation</span>';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span>';
echo '</button>';
echo '<a class="navbar-brand" href="index.html">';
echo '<img src="assets/img/logo_design_100.png" alt="logo" style="width:60px;height:60px;border:0;">';
echo '</a>';
echo '</div>';
echo '<div class="navbar-collapse collapse">';
echo '<ul class="nav navbar-nav navbar-right">';
echo '<li class="active"><a href="index.html">Home</a></li>';
echo '<li><a href="about.html">About</a></li>';
echo '<li><a href="index.html">Works</a></li>';
echo '<li><a href="contact.html">Contact</a></li>';
echo '</ul>';
echo '</div><!--/.nav-collapse -->';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div id="headerwrapcontact">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12 col-lg-offset-0">';
echo '<h1> Interested?</h1>';
echo '<h2>Contact me below</h2>';
echo '</div>';
echo '</div><!--/row -->';
echo '</div> <!-- /container -->';
echo '</div><!--/headerwrap -->';
echo '';
echo '<hr class="style1">';
echo '';
echo '<!-- +++++ Contact Section +++++ -->';
echo '<div class="container">';
echo '<script src='https://www.google.com/recaptcha/api.js'></script>';
echo '<div class="form-container">';
echo '<h1>';
echo 'Contact me';
echo '</h1>';
echo '<form method="post" id="reused_form" >';
echo '<div class="form-group">';
echo '<input id="name" type="text" name="Name" class="form-control" placeholder="Enter name" required>';
echo '</div>';
echo '<div class="form-group">';
echo '<input id="email" type="email" name="Email" class="form-control" placeholder="Enter email" required>';
echo '</div>';
echo '<textarea id="message" name="Message" class="form-control" rows="6" placeholder="Enter your message" required></textarea>';
echo '<div class="g-recaptcha" data-sitekey="6LfJbmAUAAAAAOneLEhyc9k89i0_eT_pnxxkq2Ok"></div>';
echo '<button type="submit" class="btn btn-success">SUBMIT</button>';
echo '</form>';
echo '<div id="success_message" style="display:none">';
echo '<h3>Submitted the form successfully!</h3>';
echo '<p>I will get back to you as soon as possible.</p>';
echo '</div>';
echo '<div id="error_message" style="width:100%; height:100%; display:none; "> <h3>Error</h3> Sorry there was an error sending your form. </div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<!-- +++++ Footer Section +++++ -->';
echo '<div id="social">';
echo '<div class="container">';
echo '<div class="row centered">';
echo '<div class="col-lg-3">';
echo '<a href="https://twitter.com/dawborn_myles" target="_blank"><i class="fa fa-twitter"></i></a>';
echo '</div>';
echo '<div class="col-lg-3">';
echo '<a href="https://www.linkedin.com/in/myles-dawborn-49350113a" target="_blank"><i class="fa fa-linkedin"></i></a>';
echo '</div>';
echo '<div class="col-lg-3">';
echo '<a href="https://github.com/mylesdawborn" target="_blank"><i class="fa fa-github"></i></a>';
echo '</div>';
echo '<div class="col-lg-3">';
echo '<a href="https://stackoverflow.com/users/6607935/milie" target="_blank"><i class="fa fa-stack-overflow"></i></a>';
echo '</div>';
echo '';
echo '</div><!--/row -->';
echo '</div><!--/container -->';
echo '</div><!--/social -->';
echo '';
echo '<div id="footerwrap">';
echo '<div class="container">';
echo '<div class="row centered">';
echo '<div class="col-lg-4">';
echo '<p><b>Android App Designer & Developer </b></p>';
echo '</div>';
echo '';
echo '<div class="col-lg-4">';
echo '<p><b>Johannesburg, South Africa.</b></p>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<p><b>mrdawborn@gmail.com</b></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div><!--/footerwrap -->';
echo '';
echo '';
echo '<!-- Bootstrap core JavaScript';
echo '================================================== -->';
echo '<!-- Placed at the end of the document so the pages load faster -->';
echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>';
echo '<script src="assets/js/bootstrap.min.js"></script>';
echo '</body>';
echo '</html>';
?>
